import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Home, Edit, Trash2, Loader2, Search, MoreVertical } from 'lucide-react';
import Layout from '../../../components/layout/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { getHouses, createHouse, updateHouse, deleteHouse } from '../../../services/houseService';
import { House } from '../../../types';

const HousesList: React.FC = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [houses, setHouses] = useState<House[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [houseToDelete, setHouseToDelete] = useState<House | null>(null);
  
  // Modal states
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<'create' | 'edit'>('create');
  const [selectedHouse, setSelectedHouse] = useState<House | null>(null);
  const [modalLoading, setModalLoading] = useState(false);
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(true);
  const [userHasEditedCode, setUserHasEditedCode] = useState(false);
  
  // Form data
  const [formData, setFormData] = useState({
    name: '',
    code: '',
    color: '',
    description: '',
  });

  // Utility function to generate house code from name
  const generateHouseCode = (name: string): string => {
    if (!name.trim()) return '';
    
    // Remove common words and generate code
    const commonWords = ['house', 'of', 'and', 'the', 'for', 'in', 'on', 'at', 'to', 'with', 'by'];
    const words = name.trim()
      .split(/\s+/)
      .filter(word => word.length > 0 && !commonWords.includes(word.toLowerCase()))
      .slice(0, 3); // Limit to first 3 significant words
    
    if (words.length === 1) {
      // Single word: take first 3-4 characters
      return words[0].substring(0, Math.min(4, words[0].length)).toUpperCase();
    } else {
      // Multiple words: create acronym or use first word
      return words.length <= 2 
        ? words.map(word => word.charAt(0)).join('').toUpperCase()
        : words[0].substring(0, 4).toUpperCase();
    }
  };

  useEffect(() => {
    fetchHouses();
  }, []);

  const fetchHouses = async () => {
    setLoading(true);
    try {
      console.log('Fetching houses...');
      const response = await getHouses();
      console.log('Houses response:', response);
      
      if (response && response.data) {
        console.log('Setting houses:', response.data || []);
        setHouses(response.data || []);
      } else {
        console.log('Houses request failed:', response);
        setHouses([]);
        toast({
          title: "Error",
          description: 'Failed to fetch houses',
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error('Error fetching houses:', error);
      setHouses([]);
      toast({
        title: "Error",
        description: 'An error occurred while fetching houses',
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteHouse = async () => {
    if (!houseToDelete) return;

    try {
      const response = await deleteHouse(houseToDelete.id);
      if (response.success) {
        toast({
          title: "Success",
          description: 'House deleted successfully',
        });
        fetchHouses();
      } else {
        toast({
          title: "Error",
          description: response.message || 'Failed to delete house',
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error('Error deleting house:', error);
      toast({
        title: "Error",
        description: 'An error occurred while deleting the house',
        variant: "destructive",
      });
    } finally {
      setHouseToDelete(null);
    }
  };

  // Handler for name input changes with auto code generation
  const handleNameChange = (value: string) => {
    setFormData(prev => ({ ...prev, name: value }));
    
    // Auto-generate code only in create mode and if user hasn't manually edited the code
    if (modalMode === 'create' && !userHasEditedCode) {
      const generatedCode = generateHouseCode(value);
      setFormData(prev => ({ ...prev, code: generatedCode }));
    }
  };

  // Handler for manual code changes
  const handleCodeChange = (value: string) => {
    setFormData(prev => ({ ...prev, code: value.toUpperCase() }));
    
    if (modalMode === 'create') {
      if (value.trim() === '') {
        // If user clears the code, re-enable auto-generation
        setUserHasEditedCode(false);
        setIsCodeAutoGenerated(true);
        const generatedCode = generateHouseCode(formData.name);
        setFormData(prev => ({ ...prev, code: generatedCode }));
      } else {
        // User is typing in the code field - mark as manually edited
        setUserHasEditedCode(true);
        setIsCodeAutoGenerated(false);
      }
    }
  };

  // Modal handlers
  const handleOpenModal = (mode: 'create' | 'edit', house?: House) => {
    setModalMode(mode);
    setSelectedHouse(house || null);
    
    if (mode === 'create') {
      setFormData({
        name: '',
        code: '',
        color: '',
        description: '',
      });
      setIsCodeAutoGenerated(true);
      setUserHasEditedCode(false);
    } else if (house) {
      setFormData({
        name: house.name,
        code: house.code,
        color: house.color || '',
        description: house.description || '',
      });
      setIsCodeAutoGenerated(false); // Don't auto-generate when editing
      setUserHasEditedCode(true); // Prevent auto-generation in edit mode
    }
    
    setModalOpen(true);
  };

  const handleCloseModal = () => {
    setModalOpen(false);
    setSelectedHouse(null);
    setFormData({
      name: '',
      code: '',
      color: '',
      description: '',
    });
    setIsCodeAutoGenerated(true);
    setUserHasEditedCode(false);
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name.trim() || !formData.code.trim()) {
      toast({
        title: "Error",
        description: 'House name and code are required',
        variant: "destructive",
      });
      return;
    }

    setModalLoading(true);
    try {
      const houseData = {
        name: formData.name.trim(),
        code: formData.code.trim(),
        color: formData.color.trim() || undefined,
        description: formData.description.trim() || undefined,
      };

      let response;
      if (modalMode === 'create') {
        response = await createHouse(houseData);
      } else if (selectedHouse?.id) {
        response = await updateHouse(selectedHouse.id, houseData);
      }

      if (response?.success) {
        toast({
          title: "Success",
          description: `House ${modalMode === 'create' ? 'created' : 'updated'} successfully`,
        });
        handleCloseModal();
        fetchHouses();
      } else {
        throw new Error(response?.error || `Failed to ${modalMode} house`);
      }
    } catch (error: any) {
      console.error(`Error ${modalMode} house:`, error);
      toast({
        title: "Error",
        description: error.message || `Failed to ${modalMode} house`,
        variant: "destructive",
      });
    } finally {
      setModalLoading(false);
    }
  };

  const filteredHouses = (houses || []).filter(house =>
    house.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    house.code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    house.description?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <Layout>
      <div className="container mx-auto p-6 space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
              <Home className="h-8 w-8 text-blue-600" />
              House Management
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              Manage school houses for student organization and competitions
            </p>
          </div>
          <Button
            intent="primary"
            onClick={() => handleOpenModal('create')}
          >
            <Plus className="h-4 w-4 mr-2" />
            Add New House
          </Button>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>All Houses</CardTitle>
            <div className="flex items-center space-x-2">
              <div className="relative flex-1 max-w-sm">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="Search houses..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex justify-center items-center py-12">
                <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
                <span className="ml-2 text-lg">Loading houses...</span>
              </div>
            ) : filteredHouses.length === 0 ? (
              <div className="text-center py-12">
                <Home className="h-12 w-12 mx-auto mb-4 text-gray-400" />
                <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
                  {searchTerm ? 'No houses found' : 'No houses yet'}
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  {searchTerm 
                    ? 'Try adjusting your search terms' 
                    : 'Get started by creating your first house'
                  }
                </p>
                {!searchTerm && (
                  <Button
                    intent="primary"
                    onClick={() => handleOpenModal('create')}
                  >
                    <Plus className="h-4 w-4 mr-2" />
                    Add New House
                  </Button>
                )}
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>House Name</TableHead>
                      <TableHead>Code</TableHead>
                      <TableHead>Color</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Students</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredHouses.map((house) => (
                      <TableRow key={house.id}>
                        <TableCell className="font-medium">
                          <Badge variant="outline">{house.name}</Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant="secondary">{house.code}</Badge>
                        </TableCell>
                        <TableCell>
                          {house.color ? (
                            <div className="flex items-center gap-2">
                              <div 
                                className="w-4 h-4 rounded-full border border-gray-300"
                                style={{ backgroundColor: house.color }}
                              />
                              <span className="text-sm">{house.color}</span>
                            </div>
                          ) : (
                            'No color'
                          )}
                        </TableCell>
                        <TableCell>{house.description || 'No description'}</TableCell>
                        <TableCell>{house.studentCount || 0}</TableCell>
                        <TableCell className="text-right">
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                <MoreVertical className="h-4 w-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" className="w-48">
                              <DropdownMenuItem onClick={() => handleOpenModal('edit', house)}>
                                <Edit className="h-4 w-4 mr-2" />
                                Edit
                              </DropdownMenuItem>
                              <DropdownMenuSeparator />
                              <DropdownMenuItem
                                onClick={() => setHouseToDelete(house)}
                                className="text-red-600 focus:text-red-600 focus:bg-red-50 dark:focus:bg-red-950"
                              >
                                <Trash2 className="h-4 w-4 mr-2" />
                                Delete
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Create/Edit Modal */}
        <Dialog open={modalOpen} onOpenChange={setModalOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>
                {modalMode === 'create' ? 'Create New House' : 'Edit House'}
              </DialogTitle>
              <DialogDescription>
                {modalMode === 'create' 
                  ? 'Add a new house to organize students for competitions and activities.'
                  : 'Update the house information.'
                }
              </DialogDescription>
            </DialogHeader>
            
            <form onSubmit={handleFormSubmit} className="space-y-4">
              <div className="grid grid-cols-1 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">House Name *</Label>
                  <Input
                    id="name"
                    value={formData.name}
                    onChange={(e) => handleNameChange(e.target.value)}
                    placeholder="e.g., Red House, Blue House"
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="code" className="flex items-center gap-2">
                    House Code *
                    {modalMode === 'create' && !userHasEditedCode && formData.name && (
                      <span className="text-xs text-blue-600 bg-blue-50 px-2 py-1 rounded">
                        Auto-generated
                      </span>
                    )}
                  </Label>
                  <Input
                    id="code"
                    value={formData.code}
                    onChange={(e) => handleCodeChange(e.target.value)}
                    placeholder={modalMode === 'create' ? "Will be auto-generated" : "e.g., RED, BLUE"}
                    required
                    className={modalMode === 'create' && !userHasEditedCode ? 'bg-gray-50 text-gray-700' : ''}
                  />
                  {modalMode === 'create' && (
                    <p className="text-xs text-gray-500">
                      {!userHasEditedCode 
                        ? "Code is auto-generated from name. You can edit it manually." 
                        : "Manual code entry mode. Clear to re-enable auto-generation."
                      }
                    </p>
                  )}
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="color">House Color</Label>
                  <Input
                    id="color"
                    type="color"
                    value={formData.color}
                    onChange={(e) => setFormData(prev => ({ ...prev, color: e.target.value }))}
                    placeholder="#FF0000"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="description">Description</Label>
                  <Textarea
                    id="description"
                    value={formData.description}
                    onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                    placeholder="Brief description of the house"
                    rows={3}
                  />
                </div>
              </div>
              
              <DialogFooter className="gap-2">
                <Button
                  type="button"
                  intent="cancel"
                  onClick={handleCloseModal}
                  disabled={modalLoading}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  intent="primary"
                  disabled={modalLoading}
                >
                  {modalLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      {modalMode === 'create' ? 'Creating...' : 'Updating...'}
                    </>
                  ) : (
                    modalMode === 'create' ? 'Create House' : 'Update House'
                  )}
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation Dialog */}
        <AlertDialog open={!!houseToDelete} onOpenChange={(open) => !open && setHouseToDelete(null)}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete House</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete "{houseToDelete?.name}"? This action cannot be undone and will remove all associated data.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <Button
                intent="cancel"
                onClick={() => setHouseToDelete(null)}
              >
                Cancel
              </Button>
              <Button
                intent="danger"
                onClick={handleDeleteHouse}
              >
                Delete
              </Button>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </Layout>
  );
};

export default HousesList;