// Comprehensive list of religions for student forms
export const RELIGIONS = [
  'Atheist',
  'Agnostic',
  'Baháʼí',
  'Buddhism',
  'Christianity',
  'Hinduism',
  'Islam',
  'Jainism',
  'Judaism',
  'Sikhism',
  'Taoism',
  'Zoroastrianism',
  'African Traditional Religion',
  'Animism',
  'Baptist',
  'Buddhist',
  'Catholic',
  'Christian',
  'Church of England',
  'Eastern Orthodox',
  'Evangelical',
  'Hindu',
  'Jehovah\'s Witness',
  'Jewish',
  'Lutheran',
  'Methodist',
  'Mormon',
  'Muslim',
  'Orthodox',
  'Pentecostal',
  'Presbyterian',
  'Protestant',
  'Quaker',
  'Roman Catholic',
  'Seventh-day Adventist',
  'Shinto',
  'Sikh',
  'Spiritual but not religious',
  'Unitarian',
  'Other',
  'Prefer not to say'
];

// Common religions for quick access (can be customized based on school's demographics)
export const COMMON_RELIGIONS = [
  'Christianity',
  'Islam',
  'Hinduism',
  'Buddhism',
  'Judaism',
  'Sikhism',
  'Other'
];