export const STATES_PROVINCES = [
  // United States
  { value: 'AL', label: 'Alabama', country: 'US' },
  { value: 'AK', label: 'Alaska', country: 'US' },
  { value: 'AZ', label: 'Arizona', country: 'US' },
  { value: 'AR', label: 'Arkansas', country: 'US' },
  { value: 'CA', label: 'California', country: 'US' },
  { value: 'CO', label: 'Colorado', country: 'US' },
  { value: 'CT', label: 'Connecticut', country: 'US' },
  { value: 'DE', label: 'Delaware', country: 'US' },
  { value: 'FL', label: 'Florida', country: 'US' },
  { value: 'GA', label: 'Georgia', country: 'US' },
  { value: 'HI', label: 'Hawaii', country: 'US' },
  { value: 'ID', label: 'Idaho', country: 'US' },
  { value: 'IL', label: 'Illinois', country: 'US' },
  { value: 'IN', label: 'Indiana', country: 'US' },
  { value: 'IA', label: 'Iowa', country: 'US' },
  { value: 'KS', label: 'Kansas', country: 'US' },
  { value: 'KY', label: 'Kentucky', country: 'US' },
  { value: 'LA', label: 'Louisiana', country: 'US' },
  { value: 'ME', label: 'Maine', country: 'US' },
  { value: 'MD', label: 'Maryland', country: 'US' },
  { value: 'MA', label: 'Massachusetts', country: 'US' },
  { value: 'MI', label: 'Michigan', country: 'US' },
  { value: 'MN', label: 'Minnesota', country: 'US' },
  { value: 'MS', label: 'Mississippi', country: 'US' },
  { value: 'MO', label: 'Missouri', country: 'US' },
  { value: 'MT', label: 'Montana', country: 'US' },
  { value: 'NE', label: 'Nebraska', country: 'US' },
  { value: 'NV', label: 'Nevada', country: 'US' },
  { value: 'NH', label: 'New Hampshire', country: 'US' },
  { value: 'NJ', label: 'New Jersey', country: 'US' },
  { value: 'NM', label: 'New Mexico', country: 'US' },
  { value: 'NY', label: 'New York', country: 'US' },
  { value: 'NC', label: 'North Carolina', country: 'US' },
  { value: 'ND', label: 'North Dakota', country: 'US' },
  { value: 'OH', label: 'Ohio', country: 'US' },
  { value: 'OK', label: 'Oklahoma', country: 'US' },
  { value: 'OR', label: 'Oregon', country: 'US' },
  { value: 'PA', label: 'Pennsylvania', country: 'US' },
  { value: 'RI', label: 'Rhode Island', country: 'US' },
  { value: 'SC', label: 'South Carolina', country: 'US' },
  { value: 'SD', label: 'South Dakota', country: 'US' },
  { value: 'TN', label: 'Tennessee', country: 'US' },
  { value: 'TX', label: 'Texas', country: 'US' },
  { value: 'UT', label: 'Utah', country: 'US' },
  { value: 'VT', label: 'Vermont', country: 'US' },
  { value: 'VA', label: 'Virginia', country: 'US' },
  { value: 'WA', label: 'Washington', country: 'US' },
  { value: 'WV', label: 'West Virginia', country: 'US' },
  { value: 'WI', label: 'Wisconsin', country: 'US' },
  { value: 'WY', label: 'Wyoming', country: 'US' },
  
  // Canada
  { value: 'AB', label: 'Alberta', country: 'CA' },
  { value: 'BC', label: 'British Columbia', country: 'CA' },
  { value: 'MB', label: 'Manitoba', country: 'CA' },
  { value: 'NB', label: 'New Brunswick', country: 'CA' },
  { value: 'NL', label: 'Newfoundland and Labrador', country: 'CA' },
  { value: 'NS', label: 'Nova Scotia', country: 'CA' },
  { value: 'ON', label: 'Ontario', country: 'CA' },
  { value: 'PE', label: 'Prince Edward Island', country: 'CA' },
  { value: 'QC', label: 'Quebec', country: 'CA' },
  { value: 'SK', label: 'Saskatchewan', country: 'CA' },
  { value: 'NT', label: 'Northwest Territories', country: 'CA' },
  { value: 'NU', label: 'Nunavut', country: 'CA' },
  { value: 'YT', label: 'Yukon', country: 'CA' },
  
  // India
  { value: 'AP', label: 'Andhra Pradesh', country: 'IN' },
  { value: 'AR', label: 'Arunachal Pradesh', country: 'IN' },
  { value: 'AS', label: 'Assam', country: 'IN' },
  { value: 'BR', label: 'Bihar', country: 'IN' },
  { value: 'CT', label: 'Chhattisgarh', country: 'IN' },
  { value: 'GA', label: 'Goa', country: 'IN' },
  { value: 'GJ', label: 'Gujarat', country: 'IN' },
  { value: 'HR', label: 'Haryana', country: 'IN' },
  { value: 'HP', label: 'Himachal Pradesh', country: 'IN' },
  { value: 'JK', label: 'Jammu and Kashmir', country: 'IN' },
  { value: 'JH', label: 'Jharkhand', country: 'IN' },
  { value: 'KA', label: 'Karnataka', country: 'IN' },
  { value: 'KL', label: 'Kerala', country: 'IN' },
  { value: 'MP', label: 'Madhya Pradesh', country: 'IN' },
  { value: 'MH', label: 'Maharashtra', country: 'IN' },
  { value: 'MN', label: 'Manipur', country: 'IN' },
  { value: 'ML', label: 'Meghalaya', country: 'IN' },
  { value: 'MZ', label: 'Mizoram', country: 'IN' },
  { value: 'NL', label: 'Nagaland', country: 'IN' },
  { value: 'OR', label: 'Odisha', country: 'IN' },
  { value: 'PB', label: 'Punjab', country: 'IN' },
  { value: 'RJ', label: 'Rajasthan', country: 'IN' },
  { value: 'SK', label: 'Sikkim', country: 'IN' },
  { value: 'TN', label: 'Tamil Nadu', country: 'IN' },
  { value: 'TG', label: 'Telangana', country: 'IN' },
  { value: 'TR', label: 'Tripura', country: 'IN' },
  { value: 'UP', label: 'Uttar Pradesh', country: 'IN' },
  { value: 'UT', label: 'Uttarakhand', country: 'IN' },
  { value: 'WB', label: 'West Bengal', country: 'IN' },
  
  // Australia
  { value: 'NSW', label: 'New South Wales', country: 'AU' },
  { value: 'QLD', label: 'Queensland', country: 'AU' },
  { value: 'SA', label: 'South Australia', country: 'AU' },
  { value: 'TAS', label: 'Tasmania', country: 'AU' },
  { value: 'VIC', label: 'Victoria', country: 'AU' },
  { value: 'WA', label: 'Western Australia', country: 'AU' },
  { value: 'ACT', label: 'Australian Capital Territory', country: 'AU' },
  { value: 'NT', label: 'Northern Territory', country: 'AU' },
  
  // Nigeria
  { value: 'AB', label: 'Abia', country: 'NG' },
  { value: 'AD', label: 'Adamawa', country: 'NG' },
  { value: 'AK', label: 'Akwa Ibom', country: 'NG' },
  { value: 'AN', label: 'Anambra', country: 'NG' },
  { value: 'BA', label: 'Bauchi', country: 'NG' },
  { value: 'BY', label: 'Bayelsa', country: 'NG' },
  { value: 'BE', label: 'Benue', country: 'NG' },
  { value: 'BO', label: 'Borno', country: 'NG' },
  { value: 'CR', label: 'Cross River', country: 'NG' },
  { value: 'DE', label: 'Delta', country: 'NG' },
  { value: 'EB', label: 'Ebonyi', country: 'NG' },
  { value: 'ED', label: 'Edo', country: 'NG' },
  { value: 'EK', label: 'Ekiti', country: 'NG' },
  { value: 'EN', label: 'Enugu', country: 'NG' },
  { value: 'FC', label: 'Federal Capital Territory', country: 'NG' },
  { value: 'GO', label: 'Gombe', country: 'NG' },
  { value: 'IM', label: 'Imo', country: 'NG' },
  { value: 'JI', label: 'Jigawa', country: 'NG' },
  { value: 'KD', label: 'Kaduna', country: 'NG' },
  { value: 'KN', label: 'Kano', country: 'NG' },
  { value: 'KT', label: 'Katsina', country: 'NG' },
  { value: 'KE', label: 'Kebbi', country: 'NG' },
  { value: 'KO', label: 'Kogi', country: 'NG' },
  { value: 'KW', label: 'Kwara', country: 'NG' },
  { value: 'LA', label: 'Lagos', country: 'NG' },
  { value: 'NA', label: 'Nasarawa', country: 'NG' },
  { value: 'NI', label: 'Niger', country: 'NG' },
  { value: 'OG', label: 'Ogun', country: 'NG' },
  { value: 'ON', label: 'Ondo', country: 'NG' },
  { value: 'OS', label: 'Osun', country: 'NG' },
  { value: 'OY', label: 'Oyo', country: 'NG' },
  { value: 'PL', label: 'Plateau', country: 'NG' },
  { value: 'RI', label: 'Rivers', country: 'NG' },
  { value: 'SO', label: 'Sokoto', country: 'NG' },
  { value: 'TA', label: 'Taraba', country: 'NG' },
  { value: 'YO', label: 'Yobe', country: 'NG' },
  { value: 'ZA', label: 'Zamfara', country: 'NG' },
  
  // United Kingdom
  { value: 'ENG', label: 'England', country: 'GB' },
  { value: 'SCT', label: 'Scotland', country: 'GB' },
  { value: 'WLS', label: 'Wales', country: 'GB' },
  { value: 'NIR', label: 'Northern Ireland', country: 'GB' },
  
  // Germany
  { value: 'BW', label: 'Baden-Württemberg', country: 'DE' },
  { value: 'BY', label: 'Bavaria', country: 'DE' },
  { value: 'BE', label: 'Berlin', country: 'DE' },
  { value: 'BB', label: 'Brandenburg', country: 'DE' },
  { value: 'HB', label: 'Bremen', country: 'DE' },
  { value: 'HH', label: 'Hamburg', country: 'DE' },
  { value: 'HE', label: 'Hesse', country: 'DE' },
  { value: 'MV', label: 'Mecklenburg-Vorpommern', country: 'DE' },
  { value: 'NI', label: 'Lower Saxony', country: 'DE' },
  { value: 'NW', label: 'North Rhine-Westphalia', country: 'DE' },
  { value: 'RP', label: 'Rhineland-Palatinate', country: 'DE' },
  { value: 'SL', label: 'Saarland', country: 'DE' },
  { value: 'SN', label: 'Saxony', country: 'DE' },
  { value: 'ST', label: 'Saxony-Anhalt', country: 'DE' },
  { value: 'SH', label: 'Schleswig-Holstein', country: 'DE' },
  { value: 'TH', label: 'Thuringia', country: 'DE' }
];

// For simple use without country filtering
export const ALL_STATES = STATES_PROVINCES.map(({ value, label }) => ({ value, label }));